routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::middleware('language')->group(function() {

    Route::get('/', [App\Http\Controllers\PhrasesController::class, 'index'])->name('home');
    Route::resource('phrases', \App\Http\Controllers\PhrasesController::class);
    Auth::routes();

});

Route::get('language/{locale}', [\App\Http\Controllers\LanguageSwitcherController::class, 'switcher'])
    ->name('language.switcher')
    ->where('locale', 'en|ru');

app/Models/Phrase.php
<?php

namespace App\Models;

use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Phrase extends Model implements TranslatableContract
{
    use HasFactory, Translatable;

    /**
     * @var string[]
     */
    public $translatedAttributes = ['phrase'];

}

app/Models/PhraseTranslation.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class PhraseTranslation extends Model
{
    use HasFactory;

    /**
     * @var bool
     */
    public $timestamps = false;

    /**
     * @var string[]
     */
    protected $fillable = ['phrase'];


}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/LanguageSwitcherController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class LanguageSwitcherController extends Controller
{
    /**
     * @param Request $request
     * @param string $locale
     * @return RedirectResponse
     */
    public function switcher(Request $request, string $locale)
    {
        $request->session()->put('locale', $locale);
        return back();
    }
}

app/Http/Controllers/PhrasesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PhraseRequest;
use App\Models\Phrase;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class PhrasesController extends Controller
{

    /**
     * @return Application|Factory|View|\Illuminate\Foundation\Application
     */
    public function index()
    {
        $phrases = Phrase::all();
        return view('phrases.index', compact('phrases'));
    }


    /**
     * @param PhraseRequest $request
     * @return RedirectResponse
     */
    public function store(PhraseRequest $request)
    {
        $phrase = new Phrase();
        $data = [
            'ru' =>
                [
                    'phrase' => $request->input('ru_phrase'),
                ]
        ];

        $phrase->create($data);
        return back();

    }


    /**
     * @param Phrase $phrase
     * @return Application|Factory|View|\Illuminate\Foundation\Application
     */
    public function show(Phrase $phrase)
    {
        return view('phrases.show', compact('phrase'));
    }


    /**
     * @param Request $request
     * @param Phrase $phrase
     * @return RedirectResponse
     */
    public function update(Request $request, Phrase $phrase)
    {
        if(!empty($request->input('en_phrase'))) {
            $data = [
                'en' =>
                    [
                        'phrase' => $request->input('en_phrase'),
                    ]
            ];
            $phrase->update($data);
        }
        if(!empty($request->input('mn_phrase'))) {
            $data = [
                'mn' =>
                    [
                        'phrase' => $request->input('mn_phrase'),
                    ]
            ];
            $phrase->update($data);
        }
        if(!empty($request->input('zh_phrase'))) {
            $data = [
                'zh' =>
                    [
                        'phrase' => $request->input('zh_phrase'),
                    ]
            ];
            $phrase->update($data);
        }
        if(!empty($request->input('tt_phrase'))) {
            $data = [
                'tt' =>
                    [
                        'phrase' => $request->input('tt_phrase'),
                    ]
            ];
            $phrase->update($data);
        }

        return back();
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">

    <!-- Scripts -->
    @vite(['resources/sass/app.scss', 'resources/js/app.js'])
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>



                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <select class="form-select" onchange="location = this.value;">
                            <option @if (session('locale') == 'en') selected @endif value="{{route('language.switcher', 'en')}}">
                                EN
                            </option>
                            <option @if (session('locale') == 'ru') selected @endif value="{{route('language.switcher', 'ru')}}">
                                RU
                            </option>
                        </select>



                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('messages.login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('messages.register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('messages.logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/phrases/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container" >
        <h3>
            @lang('messages.phrases')
        </h3>
        <div>
            @foreach($phrases as $phrase)
                <h5><a href="{{route('phrases.show', ['phrase' => $phrase])}}">{{$phrase->translate('ru')->phrase}}</a></h5>
            @endforeach
        </div>
            @if(Auth::check())
                <div>
                    <h5>
                        @lang('messages.create_new_phrase')
                    </h5>

                    <form method="post" action="{{route('phrases.store')}}">
                        @csrf

                        <div class="form-group mb-3">
                            <label for="ru_phrase">@lang('messages.phrase')</label>
                            <input name="ru_phrase" type="text" class="form-control border-success  @error('phrase') is-invalid border-danger @enderror"
                                   id="ru_phrase">
                        </div>
                        @error('phrase')
                        <p class="text-danger">{{ $message }}</p>
                        @enderror

                        <button type="submit" class="btn btn-primary">@lang('messages.save_phrase')</button>
                    </form>
                </div>
            @endif
    </div>

@endsection

resources/views/phrases/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <dv>
            <h3>@lang('messages.can_translate') "{{$phrase->translate('ru')->phrase}}"</h3>
        </dv>


        @if(Auth::check())
            <form method="post" action="{{route('phrases.update', ['phrase' => $phrase])}}">
                @method('put')
                @csrf
                <input type="hidden" id="phrase_id" value="{{$phrase->id}}">
                @if(!empty($phrase->translate('ru')->phrase))
                    <h4>{{$phrase->translate('ru')->phrase}}</h4>
                @else
                    <div class="form-group">
                        <label for="ru_phrase">@lang('messages.russian')</label>
                        <input name="ru_phrase"  type="text" class="form-control"
                               id="ru_phrase">
                    </div>
                @endif
                @if(!empty($phrase->translate('en')->phrase))
                    <h4>{{$phrase->translate('en')->phrase}}</h4>
                @else
                    <div class="form-group">
                        <label for="en_phrase">@lang('messages.english')</label>
                        <input name="en_phrase"  type="text" class="form-control"
                               id="en_phrase">
                    </div>
                @endif
                @if(!empty($phrase->translate('mn')->phrase))
                    <h4>{{$phrase->translate('mn')->phrase}}</h4>
                @else
                    <div class="form-group">
                        <label for="mn_phrase">@lang('messages.mongol')</label>
                        <input name="mn_phrase" type="text" class="form-control"
                               id="mn_phrase">
                    </div>
                @endif
                @if(!empty($phrase->translate('zh')->phrase))
                    <h4>{{$phrase->translate('zh')->phrase}}</h4>
                @else
                    <div class="form-group">
                        <label for="zh_phrase">@lang('messages.china')</label>
                        <input name="zh_phrase" type="text" class="form-control"
                               id="zh_phrase" >
                    </div>
                @endif
                @if(!empty($phrase->translate('tt')->phrase))
                    <h4>{{$phrase->translate('tt')->phrase}}</h4>
                @else
                    <div class="form-group">
                        <label for="tt_phrase">@lang('messages.tatar')</label>
                        <input name="tt_phrase" type="text" class="form-control"
                               id="tt_phrase" >
                    </div>
                @endif
                <button type="submit" class="btn btn-primary">@lang('messages.save_phrase')</button>
            </form>
        @else
            @if(!empty($phrase->translate('ru')->phrase))
                <div>
                    <b>@lang('messages.translate_ru')</b><br>
                    <h5>
                        {{$phrase->translate('ru')->phrase}}
                    </h5>
                </div>
            @endif

            @if(!empty($phrase->translate('en')->phrase))
                <div>
                    <b>@lang('messages.translate_en')</b><br>
                    <h5>
                        {{$phrase->translate('en')->phrase}}
                    </h5>
                </div>
            @endif

            @if(!empty($phrase->translate('mn')->phrase))
                <div>
                    <b>@lang('messages.translate_mn')</b><br>
                    <h5>
                        {{$phrase->translate('mn')->phrase}}
                    </h5>
                </div>
            @endif
            @if(!empty($phrase->translate('zh')->phrase))
                <div>
                    <b>@lang('messages.translate_zh')</b><br>
                    <h5>
                        {{$phrase->translate('zh')->phrase}}
                    </h5>
                </div>
            @endif
            @if(!empty($phrase->translate('tt')->phrase))
                <div>
                    <b>@lang('messages.translate_tt')</b><br>
                    <h5>
                        {{$phrase->translate('tt')->phrase}}
                    </h5>
                </div>
            @endif
        @endif
    </div>

@endsection